// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/users": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/users";
  };
  "./layouts/Default.tsx": {
    id: "home";
    page: "/";
  } | {
    id: "layouts/Default";
    page: "/users";
  };
  "./routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "./routes/users.tsx": {
    id: "routes/users";
    page: "/users";
  };
};

type RouteModules = {
  "root": typeof import("./client/root.tsx");
  "home": typeof import("./client/./layouts/Default.tsx");
  "routes/home": typeof import("./client/./routes/home.tsx");
  "layouts/Default": typeof import("./client/./layouts/Default.tsx");
  "routes/users": typeof import("./client/./routes/users.tsx");
};